name: 'Enable KVM'
description: 'Enables hardware accelerated Android virtualization on Actions Linux larger hosted runners. This action is required for Android emulator support in GitHub Actions.'
author: 'GetStream'

runs:
  using: "composite"
  steps:
    - name: Enable KVM group permissions
      shell: bash
      run: |
        # Create udev rule for KVM device
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        
        # Reload udev rules and trigger KVM device
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

# Usage examples:
# 1. Basic usage:
#    - uses: GetStream/actions_workflows/actions/enable-kvm@main
#
# 2. In a workflow with Android emulator:
#    jobs:
#      test:
#        runs-on: ubuntu-latest
#        steps:
#          - uses: actions/checkout@v4
#          - uses: GetStream/actions_workflows/actions/enable-kvm@main
#          - name: Run Android tests
#            run: ./gradlew connectedCheck
