name: 'Setup Ruby'
description: 'Sets up Ruby environment with version 3.1 and enables bundler caching for faster dependency installation.'
author: 'GetStream'

inputs:
  ruby-version:
    description: 'Ruby version to install (e.g., 3.0, 3.1, 3.2)'
    required: false
    default: '3.1'
  bundler-cache:
    description: 'Whether to cache bundler dependencies'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: ${{ inputs.bundler-cache }}

# Usage examples:
# 1. Basic usage (Ruby 3.1 with bundler cache):
#    - uses: GetStream/android-ci-actions/actions/setup-ruby@main
#
# 2. Specific Ruby version:
#    - uses: GetStream/android-ci-actions/actions/setup-ruby@main
#      with:
#        ruby-version: '3.2'
#
# 3. Without bundler cache:
#    - uses: GetStream/android-ci-actions/actions/setup-ruby@main
#      with:
#        bundler-cache: 'false'
