name: 'Setup Java'
description: 'Sets up Java environment with configurable version and distribution. Uses Adopt distribution and enables Gradle caching by default.'
author: 'GetStream'

inputs:
  java-version:
    description: 'Java version to install (e.g., 8, 11, 17, 21)'
    required: false
    default: '17'
  distribution:
    description: 'Java distribution to install (adopt, temurin, zulu, amazon, microsoft)'
    required: false
    default: 'adopt'

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
        cache: 'true'

# Usage examples:
# 1. Basic usage (JDK 17 with Adopt):
#    - uses: GetStream/actions_workflows/actions/setup-java@main
#
# 2. Specific Java version:
#    - uses: GetStream/actions_workflows/actions/setup-java@main
#      with:
#        java-version: '21'
#
# 3. Different distribution:
#    - uses: GetStream/actions_workflows/actions/setup-java@main
#      with:
#        distribution: 'temurin'
